// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmmMUhzrzptILMVnVntZ3cIgrnnydW8Pc',
    appId: '1:906274384635:web:58bc9a7374d002c2c61e5e',
    messagingSenderId: '906274384635',
    projectId: 'spelet-2',
    authDomain: 'spelet-2.firebaseapp.com',
    storageBucket: 'spelet-2.appspot.com',
    measurementId: 'G-3CFD6HHLNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUcXO7DvLTbf18axRPWaoRAeJB4675guo',
    appId: '1:906274384635:android:b6131cffbe6bf837c61e5e',
    messagingSenderId: '906274384635',
    projectId: 'spelet-2',
    storageBucket: 'spelet-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHp0fh9YoXv6L564zH-n1QdLw6sErF3mA',
    appId: '1:906274384635:ios:c78d2f533ccbe205c61e5e',
    messagingSenderId: '906274384635',
    projectId: 'spelet-2',
    storageBucket: 'spelet-2.appspot.com',
    iosBundleId: 'com.example.speletV3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHp0fh9YoXv6L564zH-n1QdLw6sErF3mA',
    appId: '1:906274384635:ios:c78d2f533ccbe205c61e5e',
    messagingSenderId: '906274384635',
    projectId: 'spelet-2',
    storageBucket: 'spelet-2.appspot.com',
    iosBundleId: 'com.example.speletV3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmmMUhzrzptILMVnVntZ3cIgrnnydW8Pc',
    appId: '1:906274384635:web:3f4fb63ce5936b5dc61e5e',
    messagingSenderId: '906274384635',
    projectId: 'spelet-2',
    authDomain: 'spelet-2.firebaseapp.com',
    storageBucket: 'spelet-2.appspot.com',
    measurementId: 'G-49KM7D3P1Y',
  );
}
